## 서버 정보
server:
  port: 8099

## DB 정보
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eatingtogether?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: eatingtogether
    password: 1234
  thymeleaf:
    cache: false

## JPA 설정 정보
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

## MultipartFile 설정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

